source 'https://gitcafe.com/akuandev/Specs.git'
platform:ios, '9.2'
pod 'SDWebImage', '~>3.7'
pod 'AFNetworking', '~> 3.0'
pod 'FMDB'
pod 'JElasticPullToRefresh'
pod 'UMengSocial’, '~>5.0’
pod "WeiboSDK", :git => "https://github.com/sinaweibosdk/weibo_ios_sdk.git" 
